import { IQuestao } from "../../interfaces";
import { A, B, C, D } from "../../interfaces";

const questoes5: IQuestao[] = [
  {
    id: "51",
    numero: 1,
    texto: `Você está avaliando o recém-nascido de 34 semanas de idade gestacional e pesando 2200g. Utilizando o gráfico abaixo, classifique o RN de acordo com a idade gestacional e adquação de peso.`,
    imagens: ["51"],
    alternativas: [
      `RN a termo e Pequeno para a idade gestacional`,
      `RN prematuro e adqueado para a idade gestacional`,
      `RN a termo e adqueado para a idade gestacional`,
      `RN prematuro e grande para a idade gestacional`,
    ],
    alternativaCorreta: B,
  },
  {
    id: "52",
    numero: 2,
    texto: `No Posto de saude você recebe uma mão preocupada pois o teste de triagem metabólica do seu filho estlá alterado. Ao avaliar o teste você observa o seguinte resultado:`,
    imagens: ["52"],
    subTexto: `Qual orienação você deve dar a essa mãe?`,
    alternativas: [
      `Não há motivos para preocupação. A alteração encontrada não tem significado nenhum e representa uma variação do normal, não há necesidade de nenhuma investigação adicional.`,
      `Orienta que a próxima etapa para investigação diagnóstica é realizar dosagem sérica de TSH e T4.`,
      `Orienta que a suspeira diagnóstica se trata de uma doença provavelmente associada à deficiência do hormônio liberador da tireotrofina no hipotálamo.`,
      `Orienta que se trata de uma situação de portador de um gene e que a criança não desenvolverá a doença.`,
    ],
    alternativaCorreta: B,
  },
  {
    id: "53",
    numero: 3,
    texto: `A Colestase é definida como redução da formaÇão ou no fluxo da bile, resultando na retenção de substâncias biliares dentro do figado. Em relação à colestase neonatal, assinale a alternativa correta.`,
    alternativas: [
      `A incterícia colestática neonatal apresenta pico do 3ro ao 5to da de vida e não dura além de duas semanas.`,
      `A colestase neonatal tem sua fisiopatologia embasada no mecanismo de adaptação perinatal das bilirrubinas e , por isso, os recém-nascidos em aleitamento materno excluisvo estão mais suscetiveis a desenvolve-la.`,
      `Pode haver uma  "colestase fisilógica" no período neonatal, decorretente de metabolismo e transporte imaturos de sais biliares.`,
      `A detecção precose da incterícia colestática e seu diagnóstico oportuno e preciso são fundamentais para o sucesso do tratamento e prognóstico.`,
    ],
    alternativaCorreta: D,
  },
  {
    id: "54",
    numero: 4,
    texto: `Em relação à colestase neonatal, assinale a afirmativa correta:`,
    alternativas: [
      `A atresia de vias biliares é a principal causa de transplanete hepático em crianças.`,
      `A idade de realização da portoenterostomia de Kasai não interfere na sobrevida do figado nativo.`,
      `São causas do colestase neonatal: síndrome de Crigler-Najjar tipo II e atresia de vias biliares.`,
      `A hiperbilirrubinemia indireta é sempre patogênica, determinando uma propedêutica específica e imediata, sendo que em alguns casos a determinação precoce da causa impacte determinantemente no prognóstico.`,
    ],
    alternativaCorreta: A,
  },
  {
    id: "55",
    numero: 5,
    texto: `A puericultura é um conjunto de ações de monitoramento de situaÇões da rotina que resultam em estratégias de promoção da saúde e prevenção de doenças, com objetivos que extrapolam uma infância saudável e alcançam a saúde do futuro do adulto. Em relação à consulta pediátrica, é CORRETO afirmar que:`,
    alternativas: [
      `O pediatra deve verificar a situação vacinal, investigar a rotina de alimentação e de sono e avaliar a relação entre pais e filhos, além de marcos do desenvolvimento.`,
      `É fundamental que o pediatra pergunte sobre o tempo diário de exposição da criança a tecnologias digitais, sendo que até os dois anos de idade o ideal são duas horas diárias.`,
      `O intervalo entre as consultas na faixa etária de dois a quatro anos deve ser de 12 meses, ou seja, uma consulta a cada ano.`,
      `As consultas de puericulturas são realizadas ambulatorialmente e se encerram quando a criança completa 5 anos de idade.`,
    ],
    alternativaCorreta: A,
  },
  {
    id: "56",
    numero: 6,
    texto: `Em relação à saúde da crianç, é correto afirmar:`,
    alternativas: [
      `A puericultura tem como base a consulta médica e sistemática, cujo foco é o tratamento de intercorrências e patologias comuns na primeira infância.`,
      `Consultas com adolescentes não são consideradas puericultura.`,
      `A freqência das consultas de puericultura deve acompanhar os riscos para cada faixa etária.`,
      `Considerando a intervenção efetiva e apropriada da puericultura, a prevenção de acidentes e o cuidado com a higiente ambiental não se enquadra entro os objetivos desta estratégia.`,
    ],
    alternativaCorreta: C,
  },
  {
    id: "57",
    numero: 7,
    texto: `Em relação à interpretação de hemograma para diagnóstico diferencial de anemias, assinale a alternativa correta:`,
    alternativas: [
      `A concentração de hemoglobina corpuscular média (CHCM) representa a concetração média de Hb por eritrócito. Na anemia ferropriva o CHCM encontra-se normal ou elevado.`,
      `A medida de intensidade de ansiocitose é apresentada pelo RDW (red cell distribution width) e encontra-se reduzido na anemia ferropriva.`,
      `Hiprocromia e microcitose com aumento da contagem de glóbulos vermelhos pode sugerir traço alfa ou beta-talassemia.`,
      `Anemia por deficiência de ácido fólico é hipercrômica e normocítica.`,
    ],
    alternativaCorreta: C,
  },
  {
    id: "58",
    numero: 8,
    texto: `A deficiência de ferro tem repercussões importante de longo prazo no desenvolvimento de habilidades cognitivas, comportamentais, linguagem, psicoemocionais e motoras da criança. Entre as açÕes para prevenção da deficiência de ferro e anemia ferropriva, encontra-se a sulementação medicamentosa profilática. Em relação às recomendações da Sociedade Brasileira de Pediatria sobre o tema, assinale a alternativa correta:`,
    alternativas: [
      `Recém nascido a termo, com peso adequado para idade gestaciona, cuja mãe não recebeu suplementação de ferro durante a gravidez, deve receber suplementação profilática a partir de 90 dias de vida até os 2 anos de idade.`,
      `Recém-nascido a termo, com peso adequado para idade gestacional, deve inicial a suplementação profilática aos 90 dias de vida, independentemente do tipo de alimentaçõa ou faotres de risco.`,
      `Recem-nascido a termo, co peso de nascimento inferior a 2500g, deve iniciar a suplementação profilática aos 90 dias de vida, com dose dobrada no segundo ano de vida.`,
      `Recém-nascido a termo, com peso adequado para idade gestacional, sem fatores de risco para anemia ferropriva não necessita de suplementação profilática`,
    ],
    alternativaCorreta: A,
  },
  {
    id: "59",
    numero: 9,
    texto: `Lactante de 1 ano vem para consula de rotina com exames solicitados. Não apresenta queixas ou alteraçÕes ao exame físico. No interrogatório alimentar, observa-se baixo consumo de proteína animal e ingesta diária de 4 mamdeiras de leite de vaca com achocolatado. Analise os exames abaixo e assinale a alternativa com melhor hipótese diagnóstica e tratamento medicamentoso:`,
    imagens: ["59"],
    alternativas: [
      `Anemia ferropriva / Ferro oral (3-6 mg de ferro elementar/kg/dia) por 6 meses`,
      `Anemia ferropriva / Ferro oral (1mg de ferro elementar/kg/dia) por 12 meses`,
      `Anemia por deficiência de B12 / Vitamina B12 intramuscular 1 vez ao mês por 6 meses`,
      `Deficiência de ferro sem anemia / Não necessita de nenhum tratamento pois não tem sintomas aparentes.`,
    ],
    alternativaCorreta: A,
  },
  {
    id: "510",
    numero: 10,
    texto: `Dentre os casos a seguir, em qual o exame de eletroforese de hemoglobina está indicado?`,
    alternativas: [
      `Criança de 5 anos com anemia microcítica e hipocrômica, ferritina = 330 mg/dL (VR = 25-90 mg/dL) e proteina C reativa = 110 mg/L (VR < 10).`,
      `Criança de 2 anos com anemia macrocítica e normocrômica, com dosagem normal de vitamina B12.`,
      `Criança de 9 anos com anemia microcítica, ferritina 55 mg/dL (VR 25-90 mg/dL) e proteina C reativa =3 (VR < 10).`,
      `Recém-nascido com teste de pezinho com resultado da triagem para hemoglobinopatias = FAS (VR= FA)`,
    ],
    alternativaCorreta: C,
  },
  {
    id: "511",
    numero: 11,
    texto: `Um paciente realizou hemograma completo como parte de uma avaliação médica de rotina. Os resultados mostraram a presença de blastos no sangue, especialmente linfoblastos. Diante desse cenário, assinale a alternativa correta:`,
    alternativas: [
      `Linfoblastos são formados a partir da linhagem mieloide multipotente que podem estar presentes na medula ossea, mas não são encontrados nos orgaos linfoides e sangue em situações normais.`,
      `Linfoblastos possuem elevado potencial miotico e são enconctrados com mais frequência na medula óssea e nos órgãos linfáticos, mas não no sangue. No caso do paciente, pode indifcar algum tipo de anormalidade.`,
      `Linfoblastos são células tronco multipotentes, contribuindo para a renovação das células do sistema imunológico, por isso se forem encontradas no sangue não há necessidade de investigações adicionais.`,
      `Linfoblastos são células-tronco progenitoras com elevada atividade miotíca e alto potencial de autorrenovação, sendo precursores das célular linfocíticas formadoras de colônias.`,
    ],
    alternativaCorreta: B,
  },
  {
    id: "512",
    numero: 12,
    texto: `Durante a avaliação de hemograma de um paciente, observou-se um aumento significativo na quantidade de bastonetes circulantes no sangue, além da presença de neutrófilos hipersegmentados. Assinale a alternatia correta em relação à interpretação desses achados clínicos:`,
    alternativas: [
      `A presença de bastonetes aumentados indica um aumento na produção de neutrófilos pela medula óssea. Neutrófilos com núcleos hipersegmentados possuem maior atividade fagocitária, resultando em uma resposta imunológica mais eficaz.`,
      `O aumento de bastonetes sugere uma reação inflamatória aguda, enquanto os neutrófilos com núcleos hipersegmentados são indicativos de uma resposta imunológica adaptativa. Essas alterações indicam uma infecção bacteriana.`,
      `A presença de bastonetes no sangue pode estar associada a uma deficiência de vitamina B12. Neutrófilos com núcleos hipersegmentados são aqueles que tem expectativa de vida nos tecidos de 1 a 2 dias.`,
      `O aumento de bastonetes pode ser uma resposta normal ao estresse físico ou ao uso de alguns medicamentos. Neutrófilos com núcleos hipersegmentados possuem mais de 5 lóbulos e podem ser menos eficientes na fagocitose, comprometendo a defesa do organismo.`,
    ],
    alternativaCorreta: D,
  },
  {
    id: "513",
    numero: 13,
    texto: `Leia as situações descritas a seguir:`,
    itens: [
      `Criança de 5 anos apresenta hemograma com neutrofilia.`,
      `Criança de 3 anos fez linfocitose, evidenciado no hemograma.`,
      `Criança de 9 anos com eosinofilia apresentada no hemograma.`,
      `Criança de 12 anos apresenta linfopenia no hemograma.`,
    ],
    subTexto: `Assinale a alternativa que corresponde às causas corretas das alterações dos hemogramas citados:`,
    alternativas: [
      `As crianças das situações I e II estão apresentando leucocitose devido a uma provável infecção bacteriana.`,
      `A linfopenia apresentada na situação IV é comum ocorrer em infecções virais.`,
      `A situação III pode ocorrer em casos de asma, rinite alérgica e parasitoses, enquanto a situação II ocorre, geralmente, em infecções virais.`,
      `A criança da situação II pode estar sendo submetida a um tratamento com imunossupressor.`,
    ],
    alternativaCorreta: C,
  },
  {
    id: "523",
    numero: 23,
    texto: `Um recém-nascido (RN) de 35 semanas apresenta crises convulsivas ainda em sala de parto. É pequeno para idade gestacional e apresenta instabilidade clínica, necessitando de internação em unidade de terapia intensiva (UTI) neonatal. Tomografia de crânio apresenta calcificações difusas e hidrocefalia, fundo de olho com coriorretinite bilateral. Não há informações sobre pre-natal. Com base na principal hipotese diagnóstica, assinale a alternativa correta:`,
    alternativas: [
      `Provalvamente trata-se de uma infecção congênita cuja aquisição ocorreu no terceiro trimestre de gestação.`,
      `Como há acometimento ocular, o tratamento deve incluir corticoide (prednisolona), independentement de alterações na análise do liquido cefalorraquidiano`,
      `O tratamento do RN deve ser iniciado o mais precocemente possível com espiramicina. Se infecção confirmada, transicionar para esquema tríplice (sulfadiazina, pirimetamina e ácido folínico).`,
      `Este caso poderia ter sido prevenido se a mãe tivesse caderneta de vacinação em dia.`,
    ],
    alternativaCorreta: B,
  },
  {
    id: "524",
    numero: 24,
    texto: `Como parte da rotina de atendimento na maternidade, uma gestante admitida em trabalho de parto faz teste rápido para sífilis com resultado REAGENTE. Realizou pré-natal adqueadamente, sem alterações nos examentes até então. Nega história prévia de sifilis. Nasce um bebê a termo, assintromático. Coletando VDRL da mão e do RN, ambos 1/8. Sobre este caso, assinale a alternativa INCORRETA:`,
    alternativas: [
      `Devem ser realizados exames complementares no RN: hemograma, radiografia de ossos longos, análise do líquido cefalorraquidiano`,
      `Como o VDRL da mãe e do RN são iguais, o RN é considerado exposto a sífilis (não infectado) e pode receber alta para seguimento ambulatorial com próxima coleta de VDRL de control com 1 mês de idade.`,
      `O resultado dos exames complementares pode modificar o esquema terapêutico desde RN:  se análise do líquido cefalorraquidiano evidenciar neurossífilis, há necessidade de tratamento com penicilina cristalina.`,
      `Este caso exige notificação no SINAN (sistema informação de agravos de notificação)`,
    ],
    alternativaCorreta: B,
  },
  {
    id: "525",
    numero: 25,
    texto: `Diante de um RN exposto à sifilis, é imprescindível que se avalie o histórico de tratamento de sifilis na gestante. Segundo o protocolo atual do Ministério da Saúde, o tratamento materno adquado inclui os seguintes itens, EXCETO:`,
    alternativas: [
      `Administração de benzilpenicilina benzatina`,
      `Tratamento finalizado até 30 dias antes do parto`,
      `Esquema trapêutico de acordo com o estágio clínico da infecção`,
      `Respeito ao intervalo recomendado entre as doses`,
    ],
    alternativaCorreta: B,
  },
  {
    id: "526",
    numero: 26,
    texto: `Em relação aos cuidados com o recém-nascido exposto ao HIV, assinale a alternativa correta:`,
    alternativas: [
      `Se mãe em uso de TARV (terapia antirretroviral) na gestão, sem falha na adesão e com CV-HIV (carga viral) indetectável no terceiro trimistre, o RN não precisa receber profilaxia medicamentosa, mas não pode ser amamentado.`,
      `RN de mão sem pre-natal ou sem uso de TARV durante a gestação são considerados de alto risco para transimissão vertical e devem receber AZT (zidovudina) por 6 semanas de vida`,
      `O esquema de profilaxia medicamentosa para RN a termo de altro risco inclui 3 medicamentos: AZT (zidovudina), 3TC (lamivudina) e RAL (raltegravir).`,
      `Ao nascimento, deve ser coletado anto-HIV para investigar se a criança adquiriu infecção por via placentária.`,
    ],
    alternativaCorreta: C,
  },
  {
    id: "527",
    numero: 27,
    texto: `Um RN pequeno para idade gestacional apresenta hepatoesplenomegalia, icterícia colestátiva, microcefalia e calcificações periventriculares. Considerando a hipótese de infecção congênita citomegalovirus (CMV), assinale a alternativa correta:`,
    alternativas: [
      `O diagnóstico diferencial com outras infecções congênitas tem pouco valor, uma vez que o quadro clínico é altamente compátivel com infecção por CMV.`,
      `O padrão outro para diagnóstico do RN é a identificação de antricorpos IgG e IgM no sange na primeira semana de vida.`,
      `O tratamento adequado iniciado ainda no período neonatal pode prevenir a perda auditiva neurossensorial`,
      `Não há nenhuma forma de prevenção da infecção congênita por CMV`,
    ],
    alternativaCorreta: C,
  },
  {
    id: "528",
    numero: 28,
    texto: `Gestantes susctetíveis à toxoplasmose devem ser orientadas sobre formas de prevenção da infecção. Assinale a alternativa que NÃO comtempla prevenção para toxoplasmose:`,
    alternativas: [
      `Evitar o consumo de carnes cruas ou malpassadas`,
      `Lavar bem frutas e outro vegetais antes do consumo`,
      `Utilizar luvas ao manipular terra`,
      `Usar luvas ao trocar fraldas de lactentes infectados`,
    ],
    alternativaCorreta: D,
  },
  {
    id: "529",
    numero: 29,
    texto: `Em relação ao aleitamento materno, assinale a alternativa correta:`,
    alternativas: [
      `Um lactante que, além do leite materno, infere água e chás, estáem aleitamento materno mist/parcial.`,
      `O colostro é um leite rico em proteínas, produzido nos primeiros dias após o parto em grande quantidade.`,
      `Recomenda-se que a amamentação seja sem restrição de horário oi de permanência de mama (livre demanda).`,
      `Se o bebê mamar por menos de 10 minutos em uma mama, possivelmente não estará recebendo o leite posterio, mais rico em calorias.`,
    ],
    alternativaCorreta: C,
  },
  {
    id: "530",
    numero: 30,
    texto: `Você atende um bebeê no seu quinto dia de vida. É um recém-nascido a termo, com peso de nascimento = 3400g. Está em aleitamento materno excluisivo (AME). Mão refere trocar fralda com urina clara 6 vezes ao dia e fezes amareladas 3-4 vezes ao dia. Ao exame, encontra-se ativo e reativo, com peso atual de 3200g. Em relaÇão ao aleitamento materno, qual sua orientação?`,
    alternativas: [
      `Manter o AME em livre demanda, evitando o uso de chupetas e mamadeiras.`,
      `Manter o AME, retornando em 4 dias para nova avaliação.`,
      `Manter o AM, mas iniciar complementação com fórmula infantil até recuperar a perda ponderal.`,
      `Manter o AME, suplementando com próprio leite materno ordenhado via translactação.`,
    ],
    alternativaCorreta: A,
  },
  {
    id: "531",
    numero: 31,
    texto: `Ao retornar ao trabalho, é importante que a lactante receba orientações adequadas para manutençao do aleitamento materno. Sobre essas orientaçÕes, segundo o Minestério da Saúde, assinale a INCORRETA:`,
    alternativas: [
      `O frasco ideal para armazenamento do leite materno é de vidro com tampa plástica rosqueável.`,
      `O leite materno pode ser armazenado em freezer por 15 dias ou na geladeira por 12 horas.`,
      `O leite pode descongelado em banho-maria e ser oferecido ao bebê preferencialmente por copo, colher ou seringa, evitando bicos artificiais`,
      `O leite materno aquecido que restou no copo ou mamadeira não deve ser congelado novamente, mas pode permanecer em geladeira e ser oferecido por até 12 horas.`,
    ],
    alternativaCorreta: D,
  },
  {
    id: "532",
    numero: 32,
    texto: `Em relação a situações de precaução na amamentação, sengundo o Minestéria da Saúde, assinale a correta:`,
    alternativas: [
      `Lactantes que vivem com HIV ou HTLV não devem amamentar.`,
      `Lactantes com tuberculose bacilífera devem amamentar com uso de máscara durante todo o tratamento.`,
      `Lactante com infecção por varicela no mês anterior ao parto não deve amamentar por um mês.`,
      `Lactante com lesões de herpes simples em uma mama deve ser orientada a não amamentar até a resolução das lesões.`,
    ],
    alternativaCorreta: A,
  },
  {
    id: "533",
    numero: 33,
    texto: `A vigilância do Desenvolvimento Neuropsicomotor faz parte dos cuidados para uma infância saudável. Ao avaliar um bebê de 18 meses, será motivo de preocupação se ele:`,
    alternativas: [
      `Não mostrar o que quer`,
      `Não reconhecer as emoções dos pais`,
      `Não chutar uma bola`,
      `Não tirar roupas largas sozinho`,
    ],
    alternativaCorreta: A,
  },
  {
    id: "534",
    numero: 34,
    texto: `Em relação ao desenvolvimento neuropsicomotor, considere as alternativas abaixo:`,
    itens: [
      `A avaliação do desenvolvimento deve ocorrer em toda as visitas de puericultura, podendo ser utilizada a Caderneta de Saúde da Criança como uma importante ferramenta neste seguimento.`,
      `O amadurecimento do sistema motor ocorre na direção céfalo-caudal, sendo que ao longo dos primeiros meses de vida o tônus flexor aumenta`,
      `O choro é a principal forma de comunicação de um bebê nos primeirs meses de vida. A aquisição da vocalização (emissao de sons diferentes do choro) inicia aos 4 meses de idade.`,
      `Espera-se que um bebê de 2 meses siga obetos ultrapassando a linha média e reaja a sons.`,
      `Aos 24 meses de idade, a criança forma frases simples compostas de 2 palavras`,
    ],
    subTexto: `Estão CORRETAS as alternativas:`,
    alternativas: [
      `Apenas I e II`,
      `Apenas II e III`,
      `I, III, IV, V`,
      `I, IV e V`,
    ],
    alternativaCorreta: D,
  },
  {
    id: "535",
    numero: 35,
    texto: `A alimentação adquada na infância não apenas contribui para saúde da criança, como também previne doenças crônicas na vida adulta. A introdução alimentar (IA) é o primeiro passo para estabelecer bons habiltos alimentares. Sobre orientações na IA, segundo a Sociedade Brasileira de Pediatria, assinale a alternatia CORRETA:`,
    alternativas: [
      `Os sucos artificiais devem ser evitados pelo risco de predispor à obesidade. Os sucos naturais podem ser oferecidos desde o início da IA, desde que não sejam adoçados.`,
      `Com o início da IA, passa a ser recomendada a oferta de água potável ao bebê, visando compensar a maior quantidade de proteínas e sais contidos nos alimentos.`,
      `O ovo pode ser oferecido desde o início da IA, exceto em bebês com história familiar de alergia. Nestes casos, deve-se esperar até o 1 ano de idade.`,
      `A higienização de frutas e hortaliças pode ser realizada com molho de bicarbonato de sódio a 1 ou 2,5%.`,
    ],
    alternativaCorreta: B,
  },
  {
    id: "536",
    numero: 36,
    texto: `Na introdução alimentar, recomenda-se apresentar ao bebê a maior diversidade possível de alimentos saudáveis. Analise as alternativas acerta da classificação de alimentos segundo o Guia Alimentar do Ministério da Saúde e assinale a INCORRETA:`,
    alternativas: [
      `Os alimentos in natura são obtidos diretamente das plantas ou dos animais e não são alterados após deixar a natureza. Os alimentos minimamente processados passam por alguma modificação (ex. pasteurização) que não envolve a adição de substâncias. Este grupo de alimentos deve ser a base da alimentação da criança (e de toda a família).`,
      `Biscoitos e bolachas doces e salgadas (com ou sem recheio), leite fermentado, cereais matinais açucarados e macarão instanâneo (massa e temper) são exemplos de alimentos ultraprocessados.`,
      `Os alimentos ultraprocessados conêm excesso de sal, gordura e açucar, além de aditivos (ex. corantes, conservantes, adoçantes e estabilizantes), portante devem ser oferecidos com cautela para crianças com menos de 2 anos.`,
      `Mesmo sendo alimentos minimamente processados, não se recomenda café, erva-mate, chá verde e chá preto para crianças.`,
    ],
    alternativaCorreta: C,
  },
  {
    id: "537",
    numero: 37,
    texto: `A incterícia neonatal é um dos sinais mais frequentes no período neonatal e é a manifestação clínica da hiperbilirrubinemia. Sobre a ictericia neonatal, é correto afirmar:`,
    alternativas: [
      `A hiperbilirrubinemia indireta é detectada na grande maioria dos recém-nascidos pré-termo, mas de forma mais leve e menos duradoura quando comparada à do RN a termo.`,
      `Quanto maior o nível sérico de bilirrubina direta, maiora a chance do RN evoluir para encefalopatia bilirrubínica aguda.`,
      `Quanto menor a idade gestacional, maior é o risco de complicações neurológicas relacionadas à hiperbilirrubinemia.`,
      `A incompatibilidade sanguínea materno-fetal ABO alerta para possibildiade de doença hemolítica e deve ser suspeitada em casos de mãe com tipagem sanguínea A ou B e RN O.`,
    ],
    alternativaCorreta: C,
  },
  {
    id: "538",
    numero: 38,
    texto: `RN prematuro tardio, IG = 36 semanas, filho de mãe com diabetes gestacional. Tipagem sanguínea do RN
    é A, Rh-negativo; tipagem sanguínea da mãe é O, Rh-negativo, Coombs indireto negativo. Evolui com icterícia com 24 horas de vida, Zona III.
     Perda de peso de 4% em aleitamento misto desde o nascimento, Sem outras alterações ao exame físico. Assinale a alternativa que 
     NÃO representa fator de risco para hiperbilirrubinemia significante neste RN:`,
    alternativas: [
      `Idade gestacional de 36 semanas`,
      `Mão diabética`,
      `Incompatibilidade sanguínea materno-fetal ABO`,
      `Perda de peso de 4%`,
    ],
    alternativaCorreta: D,
  },
  {
    id: "539",
    numero: 39,
    texto: `Analise as seguintes sentenças sobre o tratamento de hiperbilirrubinemia indireta neonatal:`,
    itens: [
      `A fototerapoa é indicada de acordo com o nível de bilirrubina sérica e 
        a idade do recém nascido em horas`,
      `O mecanismo de ação da fototerapia consiste na degradação da bilirrubina através da
         absorção de energia luminosa pela epiderme e tecido subcutâneo do RN, sendo
          eliminada pelo suor.`,
      `A efiácia da fototerapia é medida através da melhora da icterícia, que ocorre
         em zonas I a V`,
      `A exsanguineotransfusão remove hemácias com anticorpos ligados e/ou crculantes, 
         leva à redução da bilirrubina e correção da anemia. Atualmente poucos casos 
         necessitam desse procedimento.`,
    ],
    subTexto: `Estão CORRETAS as sentenças`,
    alternativas: [
      `Apenas II`,
      `I, II, III`,
      `I, IV`,
      `Todas as alternativas estão corretas`,
    ],
    alternativaCorreta: C,
  },
  {
    id: "540",
    numero: 40,
    texto: `Em relação às possíveis etilogias da hiperbilirrubina indireta no 
    período neonatal, assinale a alternativa correta:`,
    alternativas: [
      `Incompatibilidade sanguínca materno-fetal, é um exemplo de etiologia atribuída à deficiência da conjugação de bilirrubina.`,
      `Baixa oferta central pode levar à icterícia por aumento da circulação êntero-hepáriva de bilirrubina.`,
      `A icterícia pelo leite materno inicia nas primeiras horas de vida e está associada à sobrecarga de bilirrubina ao hepatócito.`,
      `Infecções bacterianas ou virais não são consideradas etiologias importantes de hiperbilirrubinemia neonatal.`,
    ],
    alternativaCorreta: B,
  },
];

export default questoes5;
